services:
  server:
    image: phonebook-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb+srv://fullstack:fullstack@learn.oxmfu.mongodb.net/phonebook?retryWrites=true&w=majority&appName=Learn
      - PORT=3000