services:
  app:
    image: phonebook-frontend-dev
    build:
      context: ./phonebook-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./phonebook-frontend:/usr/src/app
    ports:
      - 5173:5173

  server:
    image: phonebook-backend-dev
    build:
      context: ./phonebook_backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./phonebook_backend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb+srv://fullstack:fullstack@learn.oxmfu.mongodb.net/phonebook?retryWrites=true&w=majority&appName=Learn
      - PORT=3000

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-reverse-proxy
    depends_on:
      - app
      - server