services:
  app:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend
      dockerfile: Dockerfile

  server:
    image: phonebook-backend
    build:
      context: ./phonebook_backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb+srv://fullstack:fullstack@learn.oxmfu.mongodb.net/phonebook?retryWrites=true&w=majority&appName=Learn
      - PORT=3000

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:81
    container_name: phonebook-reverse-proxy
    depends_on:
      - app
      - server